language: php
php:
  - '7.1'
  - '7.2'

addons:
  artifacts: true

before_install:
  - pear config-set preferred_state beta
  - if [ ! `php -m | grep apcu | wc -l` -gt 0 ]; then yes '' | pecl install apcu ; sudo bash -c "echo extension=apcu.so > `php -i | grep 'Loaded Configuration File' | sed -r 's/^.* => (.*)$/\1/'`" ; sleep 0; fi

install:
  - if [ `php -r 'echo version_compare(PHP_VERSION, "7.2.0") < 0?"1":"0";'` -gt 0 ]; then composer update ; fi
  - if [ `php -r 'echo version_compare(PHP_VERSION, "7.2.0") > 0?"1":"0";'` -gt 0 ]; then composer install ; fi

before_script:
  - mkdir config/jwt
  - openssl genrsa -passout pass:test -out config/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:test -pubout -in config/jwt/private.pem -passout pass:test -out config/jwt/public.pem
  - cd frontend && npm install && npm run test && npm run build
  - cp phpunit.xml.dist phpunit.xml

script:
  - bin/phpunit --coverage-clover=coverage.xml

